### ISSUE TITLE
Environmental > Sobriety > Hardware acceleration

### ISSUE THREAD

**Issue by olegoaer** [cnumr/best-practices-mobile#16]
Hardware acceleration for 2D rendering is enabled by default if your Target API level is >=14. Because of the increased resources required to enable hardware acceleration, it can greatly lower the battery life of a device, especially wearables (e.g. Watch). However, it can be explicitly disabled at the application level with the specific attribute `<application android:hardwareAccelerated="false">` in the Android manifest file.

**Comment by olegoaer** [comment]
@gaelfoppolo Same for iOS?

**Comment by gaelfoppolo** [comment]
I don't think there is a way to enable or disable global hardware acceleration on iOS.

**Comment by olegoaer** [comment]
Successfully integrated
