### ISSUE TITLE
Disable Obfuscation should not be listed as a best practice

### ISSUE THREAD

**Issue by FannyDemey** [cnumr/best-practices-mobile#20]
Hi 
First, thank you for this list of best practices for mobile app. That's a really good starting point when we wonder what matters regarding that subject.
I would like to share my concern about the practice "Disable Obfuscation". I think it should not be listed here, as even if it can be a best practice for power consumption at runtime, it is for sure a very bad practice in term of security. 
Also, I don't know if we are able to quantify the improvement regarding power consumption versus the other main advantage of obfuscation which is to reduce the app size by shortening the names and package used in the code.

Finally, I think that a list of best practices to make apps more sustainable, should not go against best practices regarding security or accessibility. For example, we would not list as a best practice : "you should not put any text alternative on images to reduce the size of your application". 

I hope this message comes to you well, as I wish here to open the discussion and not to criticise the work that has been done.

**Comment by olegoaer** [comment]
Hi Fanny.

Thanks for your message. 

In the specific case of `Disable Obfuscation`, it comes from a rather old research paper "[How Does Code Obfuscation Impact Energy Usage?](https://onlinelibrary.wiley.com/doi/am-pdf/10.1002/smr.1762)".  It may not be relevant in 2023, and I'm willing to remove it from the repository.

However, beyond this specific case, I firmly believe that sustainability is a separate concern that can sometimes conflict with other quality concerns, such as security. When that happens, the developer has to prioritise its objective.

- Do you think the code smell Disable Obfuscation still makes sense?
- Do you have any other ideas for new Android code smells?

**Comment by FannyDemey** [comment]
Hi @olegoaer 
Thanks for your reply. I believe indeed that as this study is a bit old, it will be better to remove this guideline. Also, I do understand your opinion regarding the fact that sustainability can sometimes conflict with subject like security, but when it does, we should at least prevent developers, so that they are aware and can actually balance the decision. 
I'll have some time to work on sustainability for Android in January , then, i'll come back here to suggest any other code smells or best practice that we should share.

**Comment by olegoaer** [comment]
Okay. I remove the code smell.
Can't wait to hear from you in January 😉
